services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: autodeploy-frontend

    ports:
      - "5173:80"

    depends_on:
      - backend

    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: autodeploy-backend

    ports:
      - "8000:8000"

    environment:
      JENKINS_URL: http://jenkins:8080
      JENKINS_PUBLIC_URL: http://localhost:8080
      JENKINS_JOB: AutoDeploy-project-job
      JENKINS_TRIGGER_TOKEN: autodeploy-trigger

    depends_on:
      - jenkins

    restart: unless-stopped


  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile

    container_name: autodeploy-jenkins

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ansible:/etc/ansible/playbooks:ro

    restart: unless-stopped


volumes:
  jenkins_home: